### ISSUE TITLE
Feature: user-can-generate-an-image

### ISSUE THREAD

**Issue by Kasiett** [Kasiett/ajax-project#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

Create a responsive form that allows users to store generated image  with description to image

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Users can generate an image by typing a description of the image to the input and click create button

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="762" alt="Screenshot 2023-04-25 at 5 48 03 PM" src="https://user-images.githubusercontent.com/64724132/234438125-11b9f4fc-b523-4e2a-93c6-b0f900ba0de0.png">
<img width="761" alt="Screenshot 2023-04-25 at 5 48 12 PM" src="https://user-images.githubusercontent.com/64724132/234438138-a58195c3-7cf7-4d8c-94fa-acb4842f1da6.png">
<img width="230" alt="Screenshot 2023-04-26 at 9 32 04 AM" src="https://user-images.githubusercontent.com/64724132/234642633-9b36f515-3f47-4e8e-98d1-dbdd7f647d88.png">
<img width="228" alt="Screenshot 2023-04-26 at 9 33 09 AM" src="https://user-images.githubusercontent.com/64724132/234642695-4a1f1932-8a75-4fad-803c-a6a3d157ed8c.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] ...Add HTML structure for the home page 
       a. Create nav bar  with anchor tags  home and my creations.
       b. Create form for the image description, make  input of the image description form `required`.
- [x] ...Add style &  layout to the  home page 
- [x] ...Listen for  'submit' event to the create button that makes an api request to generate an image
      a. Once the image is generated, loop over the results, and create a DOM tree for the image. Append the result to the DOM
     b.set the  generated url  as a  value to the src attribute of the created image node .
- [ ] 
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
