### ISSUE TITLE
Feature: user-can-update-existing-image

### ISSUE THREAD

**Issue by Kasiett** [Kasiett/ajax-project#2]
## ⚙️ Feature
Edit
> ##### What capability will users have when this feature is merged?
Users will be able to edit the description of an existing image.

user-can-update-existing-image
> ##### A description of how the application will work from the perspective of the user.
Users will be able to edit the description of an existing image. click on the pen icon and make the desired changes. Once user have made the changes and click the save button the image will update with the new description.

Allow users to edit description for img by clicking pen icon.
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="706" alt="Screenshot 2023-04-30 at 8 23 31 PM" src="https://user-images.githubusercontent.com/64724132/235399035-9c38fefc-fb89-40a2-a676-137efc58c3ad.png">
<img width="200" alt="Screenshot 2023-04-30 at 8 23 58 PM" src="https://user-images.githubusercontent.com/64724132/235399075-2eee288a-2772-4f4e-9378-6bb04357e68b.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] ...Add event listener to pen icon
- [x] a. loop through data.entries and find the id of the edited img, and pass it to the form 
- [x] b. change the create btn to save 
- [x] c. delete editing img from the DOM and update it with edited img  call generateImg function.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
